### ISSUE TITLE
dev: add more test coverage for the incremental merkle tree

### ISSUE THREAD

**Issue by JordyRo1** [astraly-labs/hyperlane_starknet#35]
The actual merkle tree hook contract 
(cf: https://github.com/astraly-labs/hyperlane_starknet/blob/main/contracts/src/contracts/hooks/merkle_tree_hook.cairo) lacks testing for the internal functions. The idea is to try every single function to avoid unexpected outputs.

**Comment by EvolveArt** [comment]
related issue #37
