### ISSUE TITLE
Hyperlane contracts feedback

### ISSUE THREAD

**Issue by aroralanuk** [astraly-labs/hyperlane_starknet#45]
https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/mailbox.cairo#L37 - local_domain should be immutable

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/mailbox.cairo#L279 - flip the order of requiredHook and hook

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/mailbox.cairo#L275 - required checks for enough gas payment for the hooks (not sure how you'll do it if it's not in the native token like in protocol_fee)

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/hooks/merkle_tree_hook.cairo#L49 - safe to remove ownable upgradeable from merkle_tree hook if mailbox is immutable

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/hooks/merkle_tree_hook.cairo#L152 - can you use a separate AbstractPostDispatchHook so you can dedupe some of the public functions definitions and supports_metadata calls

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/client/mailboxclient.cairo#L2 - should this be called mailboxClientProxy?

https://github.com/astraly-labs/hyperlane_starknet/blob/24f4e31b92af3ae3c0e418d66c24ab49ef0d3fa7/contracts/src/contracts/isms/aggregation/aggregation.cairo#L141 - the solidity impl has the modules as static whereas the cairo impl can be modified and ownable. This is a slightly different behavior-wise because the ism owner which doesn't need to be mailbox owner can change the modules before a message is verified. I'm nitpicking here, so it shouldn't block anything but just pointing it out. Same with the multisigISMs.

**Comment by JordyRo1** [comment]
**Local Domain Immutable** : got it, we cannot specify directly on the storage that the variable is immutable, but the only way to change the value of the local domain is through  the line `self.local_domain.write()`. I will remove the possibility to do for the owner

**Comment by Josh-121** [comment]
Alright. I'm quite familiar with tackling such issues, however this will be my first contribution if assigned. I can deliver this within a day
