### ISSUE TITLE
Audit: Aggregation ISM Metadata verification

### ISSUE THREAD

**Issue by JordyRo1** [astraly-labs/hyperlane_starknet#48]
## Issue 

In the current Aggregation ISM implementation, the `has_metadata` verification returns false only if the metadata object overflows (which can happen if the object is empty). In the case where the metadata is full, it will always return true, even if the metadata range is set to 0 for this ISM 

## Solution 

In the metadata function instead of simply returning true, we must return `start > 0`, to make sure cover the case where the metadata ranges provides 0 as index ( which is impossible given that the metadata ranges occupies this part).

**Comment by Iwueseiter** [comment]
@JordyRo1 can I work on this?
