### ISSUE TITLE
Audit: concatenate_input upbyte management 

### ISSUE THREAD

**Issue by JordyRo1** [astraly-labs/hyperlane_starknet#64]
## Actual output

- The actual version does not cover the case for example where we have 0x01FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, since the upper byte will return 0x02 instead of 0x01 (edge case)

## Solution

 - Use instead the bitshift library, which make safely this operation

**Comment by Jemiiah** [comment]
can I work on this issue
